### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by eunju6460** [TheNumbat/GPU-RT#1]
log.txt

vulkan.cpp:1872 [info] Selecting GPU: NVIDIA GeForce RTX 3070 Laptop GPU
vulkan.cpp:1304 [info] [VK] Inserted device layer "VK_LAYER_KHRONOS_validation" (C:\VulkanSDK\1.2.198.1\Bin\.\VkLayer_khronos_validation.dll) (0)
vulkan.cpp:1316 [info] 	using INSTANCE: ? (1856593728864)
vulkan.cpp:1304 [info] [VK] Failed to find vkGetDeviceProcAddr in layer "C:\WINDOWS\System32\DriverStore\FileRepository\u0371609.inf_amd64_4e62b6f5d546d70a\B371320\.\amdvlk64.dll" (0)
vulkan.cpp:1316 [info] 	using INSTANCE: ? (1856593728864)
vulkan.cpp:1304 [info] [VK] Inserted device layer "VK_LAYER_NV_optimus" (C:\WINDOWS\System32\DriverStore\FileRepository\nvtfig.inf_amd64_64477ef971b813ed\.\nvoglv64.dll) (0)
vulkan.cpp:1316 [info] 	using INSTANCE: ? (1856593728864)
vulkan.cpp:1304 [info] [VK]        Using "NVIDIA GeForce RTX 3070 Laptop GPU" with driver: "C:\WINDOWS\System32\DriverStore\FileRepository\nvtfig.inf_amd64_64477ef971b813ed\.\nvoglv64.dll" (0)
vulkan.cpp:1316 [info] 	using INSTANCE: ? (1856593728864)

**Comment by eunju6460** [comment]
<img width="1280" alt="error" src="https://github.com/TheNumbat/GPU-RT/assets/52093930/7b972e6b-795d-4acd-885e-f23daa34e161">

**Comment by TheNumbat** [comment]
Sorry, didn't see this earlier. I've updated the ImGui Vulkan backend and it now runs for me, can you try again?

**Comment by eunju6460** [comment]
it fixed thx
